#ifndef NVE_LOGCATEGORY_H
#define NVE_LOGCATEGORY_H

#include <SDL3/SDL_log.h>

enum LogCategory
{
    NVE_LOG_CATEGORY_ENGINE = SDL_LOG_CATEGORY_CUSTOM,
    NVE_LOG_CATEGORY_ASSETS,
    NVE_LOG_CATEGORY_PROPSYS,
};

#endif // NVE_LOGCATEGORY_H
