#ifndef NVE_BLITTYPE_H
#define NVE_BLITTYPE_H

enum BlitType
{
    BLIT_TRANSPARENT_MASK = 0,
    BLIT_NORMAL = 1,
    BLIT_BLEND_BLACK_BIAS = 2,
    BLIT_BLEND_TEST_LIGHT = 3,
    BLIT_BLIT_AS_SHADOW = 4,
    BLIT_NORMAL_SCALE = 5,
    BLIT_AMPLIFY_LIGHT = 6
};

#endif // NVE_BLITTYPE_H
