# Generate a C header from a binary file
file(READ ${INPUT_FILE} HEX_DATA HEX)
string(LENGTH "${HEX_DATA}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

string(REGEX MATCHALL "([0-9a-f][0-9a-f])" HEX_LIST "${HEX_DATA}")

set(HEADER_CONTENT "/* Generated by CMake. Do not edit. */\n")
string(APPEND HEADER_CONTENT "unsigned char ${VAR_NAME}[] = {\n    ")

set(COUNTER 0)
foreach(HEX_VAL ${HEX_LIST})
    string(APPEND HEADER_CONTENT "0x${HEX_VAL}, ")
    math(EXPR COUNTER "${COUNTER} + 1")
    if(COUNTER EQUAL 12)
        string(APPEND HEADER_CONTENT "\n    ")
        set(COUNTER 0)
    endif()
endforeach()

string(APPEND HEADER_CONTENT "\n};\n")
string(APPEND HEADER_CONTENT "unsigned int ${VAR_NAME}_len = ${BYTE_COUNT};\n")

file(WRITE ${OUTPUT_FILE} "${HEADER_CONTENT}")
